//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursework1
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> name_type { get; set; }
        public Nullable<int> provider_name { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual provider provider { get; set; }
        public virtual type_product type_product { get; set; }
    }
}
